# permissions for end users to edit awslicenses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: awslicense-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: camunda-aws-license-operator
    app.kubernetes.io/part-of: camunda-aws-license-operator
    app.kubernetes.io/managed-by: kustomize
  name: awslicense-editor-role
rules:
- apiGroups:
  - camunda.io
  resources:
  - awslicenses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - camunda.io
  resources:
  - awslicenses/status
  verbs:
  - get
